#pragma once
#include <iostream>
#include <ostream>
#include <istream>
#include <string>
#include <vector>
#include <map>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <memory>
#include <utility>
#include <tuple>
#include <functional>
#include <type_traits>
#include <limits>
#include <list>
#include <queue>
#include <stack>
#include <deque>
#include <forward_list>
#include <array>
#include <chrono>
#include <thread>
#include <mutex>
#include <condition_variable>
#include <initializer_list>
#include <iterator>
#include <limits>
#include <new>
#include <numeric>
#include <optional>
#include <ostream>
#include <ranges>
#include <regex>
#include <fstream>
#include <cctype>